export const CREATE = 'CREATE'
export const DELETE = 'DELETE'
export const UPDATE = 'UPDATE'
export const ADD_COMMENT = 'ADD_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'